version: '2.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "./data:/data/db"
      
  trudesk-dev-service:
    container_name: trudesk-dev-service  
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8118:8118"
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    environment:
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
      USE_XFORWARDIP: "true"
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
      TRUDESK_EMAIL: ${TRUDESK_EMAIL}
      TRUDESK_USERNAME: ${TRUDESK_USERNAME}
      TRUDESK_PASSWORD: ${TRUDESK_PASSWORD}
